name: wui_builder
version: 0.6.0
homepage: https://github.com/davidmarne/wui_builder
author: David Marne <davemarne@gmail.com>
description: A ui framework for dart web apps that leverages a virtual dom.

dependencies:
  meta: ^1.0.0

dev_dependencies:
  analyzer: ^0.32.0
  build_runner: ^0.9.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
      
environment:
  sdk: ">=1.23.0 <2.0.0"
