name: wui_builder
version: 0.5.0
homepage: https://github.com/davidmarne/wui_builder
author: David Marne <davemarne@gmail.com>
description: A ui framework for dart web apps that leverages a virtual dom.

dependencies:
  meta: ^1.0.0

dev_dependencies:
  analyzer: '>=0.29.0 <0.31.0'
  coverage: ^0.9.0
  html: ^0.13.2
  dart_dev: ^1.0.0
  dart_style: '>=0.2.4 <2.0.0'
  test: ^0.12.0
      
environment:
  sdk: ">=1.23.0 <2.0.0"
