name: home_page
version: 0.0.0
author: David Marne <davemarne@gmail.com>

dependencies:
  prettify: ^0.2.1
  wui_builder:
    path: ../

dev_dependencies:
  build: '>=0.10.0 <0.12.0'
  build_runner: ^0.6.0
  built_value_generator: ^4.1.0
  dart_style: '>=0.2.4 <2.0.0'
  source_gen: ^0.7.0
  yaml: ^2.1.13

transformers:
  - $dart2js

environment:
  sdk: ">=1.23.0 <2.0.0"

web:
  compiler:
    debug: dartdevc
