name: docs
version: 0.0.0
author: David Marne <davemarne@gmail.com>

dependencies:
  prettify: ^0.2.1
  wui_builder:
    path: ../../

dev_dependencies:
  analyzer: ^0.32.0
  build_runner: ^0.9.0
  build_web_compilers: ^0.4.0

environment:
  sdk: ">=1.23.0 <2.0.0"